blog/urls.py
from django.conf.urls import url,include

from blogCMS import  settings

from  blog import views
urlpatterns = [
    url(r'^poll/$', views.poll),
    url(r'^comment/$', views.comment),
    url(r'^backend/$', views.backendIndex),
    url(r'^backend/addArticle/$', views.addArticle),
    url(r'^commentTree/(?P<article_id>\d+)$', views.commentTree),
    url(r'^(?P<username>.*)/articles/(?P<article_id>\d+)', views.articleDetail),
    url(r'^(?P<username>.*)/(?P<condition>tag|category|date)/(?P<para>.*)', views.homeSite),
    url(r'^(?P<username>.*)', views.homeSite,name="aaa"),

]

blogCMS/urls.py
from django.conf.urls import url,include
from django.contrib import admin

from django.views.static import serve
from blogCMS import  settings
from blog.views import pcgetcaptcha,pcajax_validate

from  blog import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/$', views.login),
    url(r'^get_validCode_img/', views.get_validCode_img),
    url(r'^index/', views.index),
    url(r'^$', views.index),
    url(r'^logout/', views.log_out),
    url(r'^article/', views.article),
    url(r'^reg/', views.reg),
    url(r'^cate/(?P<site_article_category>.*)/$', views.index),
    url(r'^blog/', include('blog.urls')),
    url(r'^uploadFile/$', views.uploadFile),


    # media 配置
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    # 滑动验证码配置

    url(r'^pc-geetest/register', pcgetcaptcha, name='pcgetcaptcha'),
    url(r'^pc-geetest/ajax_validate', pcajax_validate, name='pcajax_validate'),

]

blog/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import AbstractUser


class UserInfo(AbstractUser):  # settings:   AUTH_USER_MODEL = "blog.UserInfo"
    """
    用户信息
    """
    nid = models.BigAutoField(primary_key=True)
    nickname = models.CharField(verbose_name='昵称', max_length=32,null=True)
    telephone = models.CharField(max_length=11, blank=True, null=True, unique=True, verbose_name='手机号码')
    avatar = models.FileField(verbose_name='头像', upload_to='avatar', default="/avatar/default.png")
    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)

    def __str__(self):
        return self.username


class Blog(models.Model):
    """
    站点信息
    """
    nid = models.BigAutoField(primary_key=True)
    title = models.CharField(verbose_name='个人博客标题', max_length=64)
    site = models.CharField(verbose_name='个人博客后缀', max_length=32, unique=True)
    theme = models.CharField(verbose_name='博客主题', max_length=32)

    user = models.OneToOneField(to='UserInfo', to_field='nid')

    def __str__(self):
        return self.title


class Category(models.Model):
    """
    博主个人文章分类表
    """
    nid = models.AutoField(primary_key=True)
    title = models.CharField(verbose_name='分类标题', max_length=32)
    blog = models.ForeignKey(verbose_name='所属博客', to='Blog', to_field='nid')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'category'
        ordering = ['title']


class Article(models.Model):
    nid = models.BigAutoField(primary_key=True)
    title = models.CharField(max_length=50, verbose_name='文章标题')
    desc = models.CharField(max_length=255, verbose_name='文章描述')
    read_count = models.IntegerField(default=0)
    comment_count = models.IntegerField(default=0)
    up_count = models.IntegerField(default=0)
    down_count = models.IntegerField(default=0)
    create_time = models.DateTimeField(verbose_name='创建时间')

    category = models.ForeignKey(verbose_name='文章类型', to='Category', to_field='nid', null=True)
    user = models.ForeignKey(verbose_name='所属用户', to='UserInfo', to_field='nid')
    tags = models.ManyToManyField(
        to="Tag",
        through='Article2Tag',
        through_fields=('article', 'tag'),
    )
    site_article_category = models.ForeignKey("SiteArticleCategory", null=True)


    def __str__(self):
        return self.title


class ArticleDetail(models.Model):
    """
    文章详细表
    """
    nid = models.AutoField(primary_key=True)
    content = models.TextField(verbose_name='文章内容', )

    article = models.OneToOneField(verbose_name='所属文章', to='Article', to_field='nid')


class Comment(models.Model):
    """
    评论表
    """
    nid = models.BigAutoField(primary_key=True)

    content = models.CharField(verbose_name='评论内容', max_length=255)
    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    up_count = models.IntegerField(default=0)

    user = models.ForeignKey(verbose_name='评论者', to='UserInfo', to_field='nid')
    article = models.ForeignKey(verbose_name='评论文章', to='Article', to_field='nid')

    parent_comment = models.ForeignKey('self', blank=True, null=True, verbose_name='父级评论')

    def __str__(self):
        return self.content


class CommentUp(models.Model):
    """
    点赞表
    """

    nid = models.AutoField(primary_key=True)
    user = models.ForeignKey('UserInfo', null=True)
    comment = models.ForeignKey("Comment", null=True)


class ArticleUp(models.Model):
    """
    点赞表
    """
    nid = models.AutoField(primary_key=True)
    user = models.ForeignKey('UserInfo', null=True)
    article = models.ForeignKey("Article", null=True)


class Tag(models.Model):
    nid = models.AutoField(primary_key=True)
    title = models.CharField(verbose_name='标签名称', max_length=32)
    blog = models.ForeignKey(verbose_name='所属博客', to='Blog', to_field='nid')
    def __str__(self):
        return self.title


class Article2Tag(models.Model):
    nid = models.AutoField(primary_key=True)
    article = models.ForeignKey(verbose_name='文章', to="Article", to_field='nid')
    tag = models.ForeignKey(verbose_name='标签', to="Tag", to_field='nid')

    def __str__(self):
        return self.article.title + " + " + self.tag.title

    class Meta:
        unique_together = [
            ('article', 'tag'),
        ]


class SiteCategory(models.Model):
    name=models.CharField(max_length=32)

    def __str__(self):
        return self.name

class SiteArticleCategory(models.Model):
    name=models.CharField(max_length=32)
    site_category=models.ForeignKey("SiteCategory")
    def __str__(self):
        return self.name

blog/forms.py
from django import forms

from django.forms import widgets,ValidationError


from blog import models
from blog.plugins import xss_plugin

class RegForm(forms.Form):

    username=forms.CharField(max_length=12,min_length=5,required=True,error_messages={
        "required":"不能为空",
    },widget=widgets.TextInput(attrs={"class":"form-control","placeholder":"username"}))

    password=forms.CharField(min_length=6,widget=widgets.PasswordInput(
        attrs={"class": "form-control", "placeholder": "password"}
    ))

    repeat_pwd=forms.CharField(min_length=6,widget=widgets.PasswordInput(
        attrs={"class": "form-control", "placeholder": "repeat_pwd"}
    ))

    email=forms.EmailField(widget=widgets.EmailInput(
        attrs={"class": "form-control", "placeholder": "email"}
    ))


    def clean_username(self):

        ret=models.UserInfo.objects.filter(username=self.cleaned_data.get("username"))
        if not ret:
            return self.cleaned_data.get("username")
        else:
            raise ValidationError("用户名已注册")

    def clean_password(self):
        data=self.cleaned_data.get("password")

        if not data.isdigit():
            return self.cleaned_data.get("password")
        else:
            raise ValidationError("密码不能全是数字")


    def clean_validCode(self):
        if self.cleaned_data.get("validCode")== self.request.session.get("validCode"):
            return self.cleaned_data.get("validCode")

        else:
            raise  ValidationError("验证码错误")
    def clean(self):
        if self.cleaned_data.get("password") == self.cleaned_data.get("repeat_pwd"):
            return self.cleaned_data

        else:
            raise  ValidationError("两次密码不一致")

    def __init__(self,request,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.request=request

class ArticleForm(forms.Form):
    title=forms.CharField(max_length=20,error_messages={"required":"不能为空"})
    content=forms.CharField(error_messages={"required":"不能为空"},
                            widget=widgets.Textarea())
    def clean_content(self):

        html_str=self.cleaned_data.get("content")
        clean_content=xss_plugin.filter_xss(html_str)
        self.cleaned_data["content"]=clean_content

        return self.cleaned_data.get("content")

templates/addArticle.html
{% extends "backendIndex.html" %}


{% block manageCon %}
    {% csrf_token %}
    <h4 style="background-color: grey">添加文章</h4>
    <form action="/blog/backend/addArticle/" method="post" novalidate>
         {% csrf_token %}
         <div>
             <label for="title">标题：</label>
             <p>{{ article_form.title }}</p>
         </div>
         <div>
             <label for="title">内容：</label>
             <p>
                 {{ article_form.content }}

             </p>
         </div>
        <p><input type="submit" value="submit"></p>
    </form>
<script>





     KindEditor.ready(function(K) {
                window.editor = K.create('#id_content',{
                        width:"600px",
                        height:"500px",
                        resizeType:0,
                        uploadJson:"/uploadFile/",
                        extraFileUploadParams:{
                           csrfmiddlewaretoken:$("[name='csrfmiddlewaretoken']").val(),
                       }

                });

     })
</script>
{% endblock %}

templates/article.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Title</title>
</head>
<body>
{% if request.user.is_authenticated %}
<a href="/comment/">评论</a>
{% else %}
 <a href="/login/">评论</a>
{% endif %}

<h1>{{ request.user.username }}</h1>


</body>
</html>

templates/article_detail.html
{% extends "homeSite.html" %}
{% block content %}
    <div class="row">
        <h3 class="article_text">{{ article_obj.title }}</h3>
        <div class="article_con">{{ article_obj.articledetail.content|safe }}</div>
    </div>
    <div class="updown row">
        <div class="buryit pull-right">
            <span class="burynum" id="bury_count"></span>
        </div>
        <div class="diggit pull-right">
            <span class="diggnum" id="digg_count">{{ article_obj.up_count }}</span>
        </div>
    </div>
    <span class="diggnum_error pull-right"></span>
    <div class="had_comment_region">
        <h5>已发表评论(评论树):</h5>
        <div class="comment_tree_list"></div>
        <h5>已发表评论(评论楼)：</h5>
        <div class="comment_list">
            {% for comment in comment_list %}

                <div class="feedbackItem">
                    <div class="row">
                        <div class="col-md-6">

                            <img src="{{ comment.user.avatar.url }}" alt="" width="30" height="30">{# 当前评论人的头像 #}
                            <a href="/blog/{{ comment.user.username }}">{{ comment.user.username }}</a>{# 当前评论的人 #}
                            发表于 {{ comment.create_time|date:"Y-m-d H:i" }}
                        </div>
                        <div class="pull-right">
                            <a href="#comment_con" class="reply_comment_btn" comment_id="{{ comment.nid }}"
                               conmment_username="{{ comment.user.username }}">回复</a>&nbsp;&nbsp;
                            <a href="">引用</a>
                        </div>
                    </div>
                    <div style="background-color: grey">
                        {% if comment.parent_comment_id %}
                            @<a href="">{{ comment.parent_comment.user.username }}</a> :&nbsp;&nbsp;&nbsp;
                            {{ comment.parent_comment.content }}
                        {% endif %}
                    </div>
                    <div>
                        {{ comment.content }}
                    </div>
                </div>

            {% endfor %}
        </div>
    </div>


    <div class="subComment_region">
        <h5>发表评论：</h5>
        <p><input type="text" id="tbCommentAuthor" class="author" disabled="disabled" size="50"
                  value="{{ request.user.username }}"></p>
        <p>评论内容：</p>

        <form action="">
            {% csrf_token %}
            <p><textarea name="" id="comment_con" cols="60" rows="10"></textarea></p>
            <input type="button" value="提交评论" class="btn btn-default commentBtn">
        </form>
    </div>
    <div class="info user_username">{{ request.user.username }}</div>



    <script>
        // 实现ajax点赞(在登录情况下进行点赞，反之返回登录页面)

        $(".diggit").click(function () {
            if ($(".info").attr("user_username")) {
                $.ajax({
                    url: "/blog/poll/",
                    type: "post",
                    data: {
                        csrfmiddlewaretoken: $("[name='csrfmiddlewaretoken']").val(),
                        article_id: "{{ article_obj.nid }}"
                    },
                    success: function (data) {
                        var data = JSON.parse(data);   // pollResponse
                        if (data.state) {
                            var val = parseInt($("#digg_count").html()) + 1;
                            $("#digg_count").html(val)
                        }
                        else if (data.is_repeat) {
                            $(".diggnum_error").html("重复提交").css("color", "red")
                        }
                    }
                })
            }
            //在这里我们要知道两个js中location属性用法：
            //pathname:设置或返回当前url的路径部分
            //search:设置或返回从问好开始的url部分（参数部分）
            else {
                location.href = "/login/?next=" + location.pathname
            }


        });
        $(".commentBtn").click(function () {
            if ($(".info").attr("user_username")) {
                var content;
                if (parent_comment_id) {
                    var index = $("#comment_con").val().indexOf("\n");     // 子评论
                    content = $("#comment_con").val().slice(index + 1)
                } else {
                    content = $("#comment_con").val()
                }

                $.ajax({
                    url: "/blog/comment/",
                    type: "POST",
                    data: {
                        csrfmiddlewaretoken: $("[name='csrfmiddlewaretoken']").val(),
                        article_id: "{{ article_obj.nid }}",
                        comment_content: content,
                        parent_comment_id: parent_comment_id

                    },
                    success: function (data) {

                        console.log(data.create_time.slice(0, 19));

                        s = '<div class="comment_item" style="border-bottom: 1px solid grey"><div class="row"> <div class="col-md-6"> <img src="{{ request.user.avatar.url}}" alt="" width="30" height="30"> <a href="/blog/{{ request.user.username }}">{{ request.user.username }}</a> 发表于 ' + data.create_time.slice(0, 19) + ' </div> <div class="pull-right"> <a href="#comment_con" class="reply_comment_btn">回复</a> <a href="">支持</a> </div> </div> <div>' + content + ' </div> </div>'

                        $(".comment_list").append(s);

                        $("#comment_con").val("")
                    }
                })
            }
            else {
                location.href = "/login/?next=" + location.pathname
            }


        });


        var parent_comment_id = null;
        $(".comment_list").on("click", ".reply_comment_btn", function () {
            if ($(".info").attr("user_username")) {
                // 文本框中显示父评论的名字
                var parent_comment_username = $(this).attr("conmment_username");
                $("#comment_con").focus();
                $("#comment_con").val("@" + parent_comment_username + "\n");

                //  获取父评论的comment_id
                parent_comment_id = $(this).attr("comment_id")
                $.ajax({
                    url: "/blog/commentTree/{{ article_obj.nid }}",
                    success: function (data) {
                        console.log(JSON.parse(data));
                        var data = JSON.parse(data);
                        var s = showCommentTree(data);
                        $(".comment_tree_list").append(s);
                    }
                });

                // 展开评论树


                function showCommentTree(comment_list) {    //  comment_list: [{"content":"1","children_list":[{}]},{"content":"2"},{"content":"3"},]
                    var html = "";

                    $.each(comment_list, function (i, comment_dict) {
                        var val = comment_dict["content"];
                        var commnent_str = '<div class="comment"><div class="content"><span>' + val + '</span></div>';

                        if (comment_dict["chidren_commentList"]) {
                            var s = showCommentTree(comment_dict["chidren_commentList"]);    // [{},{}]
                            commnent_str += s
                        }

                        commnent_str += "</div>";
                        html += commnent_str
                    });

                    return html
                }
            }
            else{
                location.href="/login/?next="+location.pathname
            }


        })
        // 获取评论树


    </script>
{% endblock %}

templates/backendindex.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Title</title>
    <script src="/static/dist/js/jquery-3.1.1.js"></script>
    <script src="/static/dist/js/bootstrap.js"></script>
    <link rel="stylesheet" href="/static/dist/css/bootstrap.css">
    <script src="/static/kindeditor/kindeditor-all.js"></script>
    <style>
        .header{
            width: 100%;
            height: 40px;
            background-color: #2aabd2;
            line-height: 40px;
        }
        .header p{
            font-size: 15px;
            color: white;
        }
        .leftMenu{
            margin-top: 150px;
        }
            .manageCon{
            margin-top: 80px;
        }

    </style>
</head>
<body>
<div class="header">
    <p>后台管理</p>
</div>
<div class="container">
    <div class="row">
        <div class="leftMenu col-md-3">
            <p><a href="">文章管理</a></p>
            <p><a href="">标签管理</a></p>
            <p><a href="">分类管理</a></p>
        </div>
        <div class="manageCon col-md-8">

            {% block manageCon %}
               <a href="/blog/backend/addArticle/"><button class="btn btn-primary add_article">添加文章</button></a>


                <table class="table table-border table-hover">
                     <tr>
                         <th>标题</th>
                         <th>评论数</th>
                         <th>点赞数</th>
                         <th>操作</th>
                         <th>操作</th>
                     </tr>

                     {% for article in article_list %}
                       <tr>
                           <td>{{ article.title }}</td>
                           <td>{{ article.comment_count }}</td>
                           <td>{{ article.up_count }}</td>
                           <td><a href=""><button class="btn btn-info">编辑</button></a></td>
                           <td><a href=""><button class="btn btn-danger">删除</button></a></td>

                       </tr>
                     {% endfor %}


                </table>

            {% endblock %}
        </div>
    </div>
</div>
</body>
</html>

templates/demo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Title</title>
</head>
<body>



<form action="/login/">
    <p><input type="text">{{ form_obj.username.error }}</p>
    <p><input type="password">{{ form_obj.password.error }}</p>
    <input type="submit">
</form>

</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Title</title>
    <script src="/static/dist/js/jquery-3.1.1.js"></script>
    <script src="/static/dist/js/bootstrap.js"></script>
    <link rel="stylesheet" href="/static/dist/css/bootstrap.css">
    <style>
        .hides{
            display: none;
        }
    </style>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">博客园</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="active"><a href="#">园子 <span class="sr-only">(current)</span></a></li>
                <li><a href="#">收藏</a></li>
                <li><a href="#">闪存</a></li>
                <li><a href="#">博问</a></li>
                <li><a href="#">新闻</a></li>
                <li><a href="#">找找看</a></li>
                <li><a href="#">班级</a></li>

            </ul>

            <ul class="nav navbar-nav navbar-right">
                {% if request.user.is_authenticated %}
                    <li><a href=""><span class="glyphicon glyphicon-user"></span>{{ request.user.username }}</a></li>
                    <li><a href="/logout/">注销</a></li>
                {% else %}
                    <li><a href="/login/">登录</a></li>
                    <li><a href="/reg/">注册</a></li>
                {% endif %}

                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">Dropdown <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Action</a></li>
                        <li><a href="#">Another action</a></li>
                        <li><a href="#">Something else here</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">Separated link</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">One more separated link</a></li>
                    </ul>
                </li>

            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>
<div class="container">
    <div class="row">
        <div class="col-md-2">
            <div class="panel panel-default">
                <div class="panel-heading">网站分类</div>
                <div class="panel-body">
                    {% for cate in cate_list %}
                        <div class="panel panel-default">
                            <div class="panel-heading cate_title">{{ cate.name }}</div>
                            <div class="panel-body hides">
                                {% for sitearticlecategory in cate.sitearticlecategory_set.all %}
                                    <p><a href="/cate/{{ sitearticlecategory.name }}">{{ sitearticlecategory.name }}</a>
                                    </p>
                                {% endfor %}
                            </div>
                        </div>

                    {% endfor %}

                </div>
            </div>
        </div>
        <div class="col-md-7">

            <div class="article_list">
                {% for article in article_list %}
                    <div class="article_item">
                        <div class="title"><a href="">{{ article.title }}</a></div>
                        <div class="row">
                            <div class="avatar col-md-2">
                                <a href="{% url 'aaa'  article.user.username %}"><img
                                        src="{{ article.user.avatar.url }}" alt="" width="60" height="60"></a>
                            </div>
                            <div class="desc col-md-10">
                                <p class="desc">{{ article.desc }}</p>
                            </div>
                        </div>
                        <div class="row">
                            <a href="/blog/{{ article.user.username }}">{{ article.user.username }}</a>&nbsp;&nbsp;&nbsp;发布于&nbsp;&nbsp;{{ article.create_time|date:"Y-m-d H:i" }}
                            <a href=""><span class="glyphicon glyphicon-comment"></span>评论({{ article.comment_count }})</a>
                            <a href=""><span class="glyphicon glyphicon-thumbs-up"></span>点赞({{ article.up_count }})</a>
                        </div>
                    </div>
                    <hr>
                {% endfor %}

            </div>
        </div>
        <div class="col-md-3">
            <div class="panel panel-default">
                <div class="panel-heading">Panel heading without title</div>
                <div class="panel-body">
                    Panel content
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading">Panel heading without title</div>
                <div class="panel-body">
                    Panel content
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading">Panel heading without title</div>
                <div class="panel-body">
                    Panel content
                </div>
            </div>
        </div>


    </div>
</div>
<script>


    $(".cate_title").mouseover(function () {
        $(this).next().slideDown(300)
    }).parent().mouseleave(function () {
        $(this).children(".panel-body").slideUp(300)
    })


</script>
</body>
</html>

templates/notFound.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Error_404_资源不存在</title>
	<style type="text/css">
	body{margin:8% auto 0;max-width: 550px; min-height: 200px;padding:10px;font-family: Verdana,Arial,Helvetica,sans-serif;font-size:14px;}p{color:#555;margin:10px 10px;}img {border:0px;}.d{color:#404040;}
	</style>
</head>
<body>
<a href="http://www.cnblogs.com/"><img src="//static.cnblogs.com/images/logo_small.gif" alt="cnblogs"/></a>
<p><b>404.</b> 抱歉! 您访问的资源不存在!</p>
<p class="d">请确认您输入的网址是否正确，如果问题持续存在，请发邮件至contact&#64;cnblogs.com与我们联系。</p>
<p><a href="/">返回网站首页</a></p>
</body>
</html>

templates/reg.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Title</title>

    <script src="/static/dist/js/jquery-3.1.1.js"></script>
    <script src="/static/dist/js/bootstrap.js"></script>

    <link rel="stylesheet" href="/static/dist/css/bootstrap.css">

    <link rel="stylesheet" href="/static/css/reg.css">
    <script src="/static/js/jquery.cookie.js"></script>

</head>
<body>



<div class="container">
    <div class="row">
        <div class="col-md-5 col-md-offset-3">
             <div class="panel panel-primary">
                <div class="panel-heading ">博客管理系统</div>
                <div class="panel-body">
                    <form>
                      {% csrf_token %}
                      <div class="form-group">
                        <label for="username">用户名</label>
                        {{ form_obj.username }}
                      </div>
                      <div class="form-group">
                        <label for="password">密码</label>
                        {{ form_obj.password }}
                      </div>

                       <div class="form-group">
                        <label for="password">确认密码</label>
                           {{ form_obj.repeat_pwd }}
                      </div>

                      <div class="form-group">
                        <label for="email">邮箱</label>
                          {{ form_obj.email }}
                      </div>

                      <div class="form-group avatar">
                        <label for="avatar">头像</label>
                        <img src="/static/img/default.png" alt="" id="avatar_img">
                        <input type="file" class="form-control" id="avatar_file" >
                      </div>


                    <input type="button" value="submit" class="btn btn-primary" id="subBtn"><span class="error"></span>

                </form>
                </div>

        </div>
    </div>
</div>

<script>
    // 头像预览

    $("#avatar_file").change(function () {

        var ele_file=$(this)[0].files[0];  //this.files
        var reader=new FileReader();
        reader.readAsDataURL(ele_file);
        reader.onload=function () {
            $("#avatar_img")[0].src=this.result
        }

    });

    $("#subBtn").click(function () {

        var formdata=new FormData();
        formdata.append("username",$("#id_username").val());
        formdata.append("password",$("#id_password").val());
        formdata.append("repeat_pwd",$("#id_repeat_pwd").val());
        formdata.append("email",$("#id_email").val());
        formdata.append("avatar_img",$("#avatar_file")[0].files[0]);

        $.ajax({
            url:"/reg/",
            type:'POST',
            data:formdata,
            contentType:false,
            processData:false,
            headers:{"X-CSRFToken":$.cookie('csrftoken')},
            success:function (data) {
{#                  console.log(data);#}
                var data=JSON.parse(data);

                if (data.user){
                    location.href="/login/"
                }
                else {

                    console.log(data.errorsList);

                   $.each(data.errorsList,function (i,j) {
                       console.log(i,j);

                       $span=$("<span>");
                       $span.addClass("pull-right").css("color","red");
                       $span.html(j[0]);
                       $("#id_"+i).after($span).parent().addClass("has-error")

                       if (i=="__all__"){
                            $("#id_repeat_pwd").after($span)
                       }
                   })


                }


            }
        })
    })
</script>



</body>
</html>